// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8e-sbva4uyfYYjgrXn9HOf4BoJNi9ReU',
    appId: '1:303675660443:web:4f63cc1f347bcb4c994e3e',
    messagingSenderId: '303675660443',
    projectId: 'fitness-app-ca0f2',
    authDomain: 'fitness-app-ca0f2.firebaseapp.com',
    storageBucket: 'fitness-app-ca0f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2CwPsNkXKXeV1Ld4KSl558RSAn5qytzU',
    appId: '1:303675660443:android:36031a4ebcd2440c994e3e',
    messagingSenderId: '303675660443',
    projectId: 'fitness-app-ca0f2',
    storageBucket: 'fitness-app-ca0f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZWy3238zkXov75XY10wX1cYxizimrc6U',
    appId: '1:303675660443:ios:ce77b4ee9c07d02e994e3e',
    messagingSenderId: '303675660443',
    projectId: 'fitness-app-ca0f2',
    storageBucket: 'fitness-app-ca0f2.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZWy3238zkXov75XY10wX1cYxizimrc6U',
    appId: '1:303675660443:ios:ce77b4ee9c07d02e994e3e',
    messagingSenderId: '303675660443',
    projectId: 'fitness-app-ca0f2',
    storageBucket: 'fitness-app-ca0f2.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8e-sbva4uyfYYjgrXn9HOf4BoJNi9ReU',
    appId: '1:303675660443:web:361615f3e69a1e09994e3e',
    messagingSenderId: '303675660443',
    projectId: 'fitness-app-ca0f2',
    authDomain: 'fitness-app-ca0f2.firebaseapp.com',
    storageBucket: 'fitness-app-ca0f2.appspot.com',
  );
}
